/**
 * Docker 相关 IPC 通道名（主进程 register + preload invoke 应与此保持一致）。
 * 新增通道时只改此处一处，并在 registerDockerIpc / preload 中接线。
 */
export const DockerIpc = {
  ping: 'docker:ping',
  info: 'docker:info',
  version: 'docker:version',
  df: 'docker:df',
  listContainers: 'docker:list-containers',
  inspectContainer: 'docker:inspect-container',
  startContainer: 'docker:start-container',
  stopContainer: 'docker:stop-container',
  restartContainer: 'docker:restart-container',
  killContainer: 'docker:kill-container',
  pauseContainer: 'docker:pause-container',
  unpauseContainer: 'docker:unpause-container',
  removeContainer: 'docker:remove-container',
  listImages: 'docker:list-images',
  inspectImage: 'docker:inspect-image',
  removeImage: 'docker:remove-image',
  pullImage: 'docker:pull-image',
  listNetworks: 'docker:list-networks',
  removeNetwork: 'docker:remove-network',
  listVolumes: 'docker:list-volumes',
  removeVolume: 'docker:remove-volume',
  logsStart: 'docker:logs:start',
  logsStop: 'docker:logs:stop',
  logsChunk: 'docker:logs:chunk',
  createRunContainer: 'docker:create-run-container',
  recreateContainer: 'docker:recreate-container',
  patchContainerRuntime: 'docker:patch-container-runtime',
  tagImage: 'docker:tag-image',
  execOnce: 'docker:exec-once',
  eventsStart: 'docker:events:start',
  eventsStop: 'docker:events:stop',
  eventsChunk: 'docker:events:chunk',
  openDocs: 'docker:open-docs',
  pruneContainers: 'docker:prune-containers',
  pruneImages: 'docker:prune-images',
  pruneNetworks: 'docker:prune-networks',
  pruneVolumes: 'docker:prune-volumes',
  pruneBuilder: 'docker:prune-builder',
  systemPrune: 'docker:system-prune',
  createNetwork: 'docker:create-network',
  createVolume: 'docker:create-volume',
  networkConnect: 'docker:network-connect',
  networkDisconnect: 'docker:network-disconnect',
  volumeUsedBy: 'docker:volume-used-by',
  containerStatsOnce: 'docker:container-stats-once',
  imageHistory: 'docker:image-history',
  saveImageTar: 'docker:save-image-tar',
  loadImageTar: 'docker:load-image-tar',
  commitContainer: 'docker:commit-container',
  exportContainerTar: 'docker:export-container-tar',
  reconnectDocker: 'docker:reconnect-docker',
} as const

export type DockerIpcChannel = (typeof DockerIpc)[keyof typeof DockerIpc]
